### ISSUE TITLE
SpiNNakerTriadGeometry.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#195]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-machine\src\main\java\uk\ac\manchester\spinnaker\machine\SpiNNakerTriadGeometry.java

What is the problem you see?
public ChipLocation getLocalChipCoordinate(HasChipLocation chip) {
        if (chip.getX() < triadWidth && chip.getY() < triadHeight) {
            return localChipCoordinates.get(chip);
        }

suspisous call to hash map

What do you think it should do instead?
make right types to get hashmap to work

What version of our software are you using?
master

**Comment by Christian-B** [comment]
Ah. Actually a good catch.

The issue here is that the method takes an Interface HasChipLocation as the parameter chip.
Doing a get on the HashMap causes the hashcode method of the actual Object to be thrown which SHOULD be different for each implementing class.

We added the method asChipLocation() for these case.

as ChipLocation methods lets each Object best determine how to repeatedly give its location.
ChipLocation returns self
Chip returns an inner object for example.
